Traceback (most recent call last):
  File "/home/shubhransu_etc/hnas_major/src/HNAS_GA_FCN_testing.py", line 137, in <module>
    best_architecture2 = genetic_algorithm(train_dir=train_dir,len_classes=2,epochs=5, num_generations=10, mutation_rate=0.15,\
  File "/home/shubhransu_etc/hnas_major/src/HNAS_GA_FCN_testing.py", line 128, in genetic_algorithm
    score = train_and_evaluate_model(model,epochs=epochs,train_dir=train_dir)
  File "/home/shubhransu_etc/hnas_major/src/HNAS_GA_FCN_testing.py", line 92, in train_and_evaluate_model
    acc = history.history['val_binary_accuracy'][len(history.history['val_binary_accuracy'])-1]
KeyError: 'val_binary_accuracy'
